name = "guid" # تأكد إن الاسم مطابق لاسم الـ worker بتاعك
main = "_worker.js"
compatibility_date = "2024-01-01"

# السطرين دول هما "السر" عشان الـ gRPC والـ Sockets يشتغلوا بدون 1101
node_compat = true

[observability]
enabled = true

